// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJS1ofJgAj3SI4v5yeFCkko3mQlP0vVGE',
    appId: '1:956447165562:web:d635b510351706dc58bfc3',
    messagingSenderId: '956447165562',
    projectId: 'new-lostify',
    authDomain: 'new-lostify.firebaseapp.com',
    databaseURL: 'https://new-lostify-default-rtdb.firebaseio.com',
    storageBucket: 'new-lostify.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACDP1ZDmS9YyVQ3AM9YFLQNNxqn1Tcc58',
    appId: '1:956447165562:android:38ba653ce2ebb19658bfc3',
    messagingSenderId: '956447165562',
    projectId: 'new-lostify',
    databaseURL: 'https://new-lostify-default-rtdb.firebaseio.com',
    storageBucket: 'new-lostify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5fvjM__jzwccsbEfNnm1SR5SY0yyvyvc',
    appId: '1:956447165562:ios:de9425a5a53372ef58bfc3',
    messagingSenderId: '956447165562',
    projectId: 'new-lostify',
    databaseURL: 'https://new-lostify-default-rtdb.firebaseio.com',
    storageBucket: 'new-lostify.firebasestorage.app',
    iosClientId: '956447165562-hgng6dfpmod9gth4i7mu4b959ob3d3a1.apps.googleusercontent.com',
    iosBundleId: 'com.lostify.app.testProject',
  );

}